### ISSUE TITLE
Does not work with pymdownx.superfences

### ISSUE THREAD

**Issue by ErliSoares** [neatc0der/mkdocs-markmap#19]
First of all thank you very much for the plugin, very useful.

Is there any possibility to tweak it to work with pymdownx.superfences? pymdownx.superfences for me is very important, thank you very much.

I found an issue, but it seems they didn't come up with a solution #17.

**Comment by neatc0der** [comment]
tl;dr: I'll need a (minimalistic) sample environment from you that reproduces the error reliably.

-------------

When an issue is raised twice, that's not a great sign for quality of the project. So, I tried to be thorough and set up a sample environment with some gimmickry to force the error. But, I was unsuccessful. The page looks just fine after doing this:

`mkdocs.yml`
```yaml
site_name: Test
nav:
  - Home: index.md
  - ...
plugins:
  - markmap:
      base_path: mindmaps
extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight(use_pygments=false)
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
```


`docs/index.md`
````markdown
# Home

```markmap
# Root

## Branch 1

## Branch 2
```

```{.py3 hl_lines="1 3" linenums="2"}
"""Some file."""
import foo.bar
import boo.baz
import foo.bar.baz
```

$$
\frac{n!}{k!(n-k)!} = \binom{n}{k}
$$

{!mindmap.mm.md!}
````

```
$ mkdocs build
WARNING -  Config value: 'extensions'. Warning: Unrecognised configuration name: extensions 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/tobi/Projects/mkdocs-markmap/test/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - subdir/index.md 
WARNING -  A relative path to '...' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to '../' is included in the 'nav' configuration, which is not found in the documentation files 
INFO    -  script downloaded: https://unpkg.com/d3@6.7.0/dist/d3.min.js 
INFO    -  script downloaded: https://unpkg.com/markmap-lib@0.11.5/dist/browser/index.min.js 
INFO    -  script downloaded: https://unpkg.com/markmap-view@0.2.6/dist/index.min.js 
INFO    -  Documentation built in 0.85 seconds 
```
