### ISSUE TITLE
Support for mkdocs-encryptcontent-plugin

### ISSUE THREAD

**Issue by andynameistaken** [neatc0der/mkdocs-markmap#26]
![image](https://user-images.githubusercontent.com/15692002/136814342-f3c04ca7-7f12-4e54-b7ad-6f99a532ae05.png)

`mkdocs.yml`:
```
# Project information
site_name: 'Code Vault'
site_description: 'Programming Notes'
site_author: 'Andrzej Zahorski'

# Repository
# repo_name: ''
# repo_url: ''

# Copyright
copyright: 'Copyright &copy; 2021 Andrzej Zahorski'

# Plugins
plugins:
  - markmap
  - search

  # - alternate-link
  # - literate-nav:
      # nav_file: SUMMARY.md
  - roamlinks
  - encryptcontent:
      password_button: True
      password_button_text: 'custome_text_button'

## Extensions
markdown_extensions:
  - footnotes
  - pymdownx.highlight:
      linenums: true           
  - pymdownx.superfences   
  - pymdownx.inlinehilite  
  - pymdownx.keys
  - pymdownx.snippets  
  - admonition
  - pymdownx.details  
  - attr_list





  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - mdx_truly_sane_lists

  - toc:
      permalink: true

# Configuration
theme:
  font:
    text: Sarala
  features:
    - search.suggest    
    - search.highlight     
    - search.share
  
  
  name: 'material'
  language: 'en'
  # logo: 'images/logo.png'
  # favicon: 'images/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: orange
      primary: red
      toggle:
        icon: material/weather-sunny
   # Configuration

theme:
  font:
    text: Roboto
  features:
    - search.suggest    
    - search.highlight     
    - search.share
    - navigation.indexes
  name: 'material'
  language: 'en'
  # logo: 'images/logo.png'
  # favicon: 'images/logo.png'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: red
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  

# Customisation
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andynameistaken


extra_css:
  - 'stylesheets/extra.css'

      
nav:
- Java:
    - Java/md-java/index.md
    - Object Oriented Programming: Java/md-java/Object-Oriented-Programming.md
    - Map: mindmap.mm.md
```

`❯ tree docs:`
```
docs
├── Java
│   ├── images
│   │   ├── bicycleObjPaint.png
│   │   ├── concepts-bikeHierarchy.png
│   │   ├── concepts-object.png
│   │   ├── package-tree.png
│   │   └── universe.jpeg
│   └── md-java
│       ├── Object-Oriented-Programming.md
│       └── index.md
├── index.md
├── mindmap.mm.md
└── stylesheets
    └── extra.css

4 directories, 10 files
```
