### ISSUE TITLE
nav tree displaying root from markmap

### ISSUE THREAD

**Issue by andynameistaken** [neatc0der/mkdocs-markmap#33]
## Config:
`mkdocs.yml`:
```yaml
site_name: test

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - markmap

```

`docs`:

`index.md`:
```
Look at this beautiful mindmap:

{!mindmap.mm.md!}
```
`mindmap.mm.md`:
```
# Root 1
* Point 1
# Root 2

## Branch 1

* Branchlet 1a
* Branchlet 1b

## Branch 2

* Branchlet 2a
* Branchlet 2b
```

`Logs`:
```
INFO     -  script downloaded: https://unpkg.com/d3@6.7.0/dist/d3.min.js
INFO     -  script downloaded: https://unpkg.com/markmap-lib@0.11.5/dist/browser/index.min.js
INFO     -  script downloaded: https://unpkg.com/markmap-view@0.2.6/dist/index.min.js
INFO     -  no markmap found: mindmap.mm
```
---
## Problem:

Root from mindmap is on nav bar:
![image](https://user-images.githubusercontent.com/15692002/138614394-5471916e-2464-49a2-a766-abcf62e2f169.png)

**Comment by neatc0der** [comment]
This easy to fix. Just adjust your file structure and add the following configuration:

1. Move your mindmaps to a different directory than `docs`, e.g. `mindmaps`.
2. Adjust the default `base_path` for `mkdocs-markmap`:

```yaml
plugins:
  - markmap:
      base_path: mindmaps
```

Then, tools crawling for other markdown files will not be able to falsely identify markmaps as content. 

Highlighting this on a troubleshooting section in the readme might be helpful, though. Thanks for pointing this out.
